Resolved issues with IOR function
GNU Fortran compiler requires the arguments to the bitwise logical IOR
(and IAND) function to have the same type.

In `IOR(i,j)`, both i and j must be integers of the same type; for example,
both must be integer*4.

Literal values, like 16, default to integer*4.

In the code below, quality_flag is integer*1 and 1 is integer*4, leading
to a compiler error.

....
../WSF_OPL/TOOLSUBS_WSF.F90:338:44:

  338 |                     quality_flag(j,i) = IOR(quality_flag(j,i), 1)  ! Ocean
      |                                            1
Error: Arguments of ‘ior’ have different kind type parameters at (1)
....

To resolve this, the size of the literal value must be appended
to the number.  Here, the literal 1 must be specified as 1_1 to indicate
that it is one byte in size.

In Fortran, integers are signed, and 1-byte integers range
from -128 to 127.  Unfortunately, this code needed to check
the most significant bit represented by unsigned 128.
Specifying 128_1 leads to an overflow error.

Thus a temporary integer*2 (2-byte) quality_flag2 variable was created.
And the bit-identifying literal values were specified as 2-byte values.
(For example, 128 was specified as 128_2).
Then the temporary quality_flag2 variable was truncated
to the quality_flag variable.