Remove "external :: system" declaration
This causes an error with the GNU Fortran compiler.  For example,

  LDT_wsf_oplMod.F90:572:(.text+0x1ceb): undefined reference to `system_`

This was added to suppress a warning issued by the Intel Fortran
compiler.